In [1]:
import numpy as np

In [24]:
#creation of numpy array = np.array 
x = np.array([1,2,3,4,5])
print(x)
print(type(x)) #ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [27]:
#shape and size
print(x.size) #total no. of elements
print(x.shape) #dimensionwise elements
print(x.ndim) #num of dimensions

5
(5,)
1


In [28]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)
print(x.size) #total no. of elements
print(x.shape) #dimensionwise elements
print(x.ndim) #num of dimensions

[[1 2 3]
 [4 5 6]]
5
(5,)
1


In [7]:
x25 = np.random.randint(1,100,(5,5))
print(x25)

[[76 46 59  2 81]
 [66 74 99 65 68]
 [61 86 88 14 88]
 [81 86 39 35 77]
 [82 28  9 12 47]]


In [12]:
xseq1 = np.arange(1,101,4)
print(xseq1)
print(xseq1.size)


[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25


In [31]:
xseq1 = np.arange(1,101,4)
print(xseq1.size,"elements")
print("=>1D MATRIX")
print(xseq1)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq1.reshape(5,5))


25 elements
=>1D MATRIX
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
=>1D MATRIX RESHAPED TO 2D
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [ ]:
xseq2 = np.linspace(1, 100, 50)
print(xseq2.size,"elements")
print("=>1D MATRIX")
print(seq2)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq2.reshape(10,5))



In [ ]:
xseq2 = xseq2.reshape(10,5)
print(xseq2d)

In [ ]:
np.one((5,5), dtype='int')

- indexing and slicing
- boolean filter
- maths and Stats
- methods


In [16]:
x25

array([[76, 46, 59,  2, 81],
       [66, 74, 99, 65, 68],
       [61, 86, 88, 14, 88],
       [81, 86, 39, 35, 77],
       [82, 28,  9, 12, 47]])

In [19]:
#first row
print(x25[0])

[76 46 59  2 81]


In [20]:
#last row
print(x25[-1])

[82 28  9 12 47]


In [21]:
print(x25[0,1]) #same as print(x25[0][1])

46


In [22]:
# 1st column
print(x25[:, 0])

# 2nd column
print(x25[:, 1])

# 3rd column
print(x25[:, -1])


[76 66 61 81 82]
[46 74 86 86 28]
[81 68 88 77 47]


In [ ]:
#column 0,1,2 idxs
print(x25[:[0,1,2]])
#same thing as above
print(x25[:, :3])

In [ ]:
print(x.dot(y))
print()
x.sum()
x.sum(axis)
